version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: npm-check-updates
    versions:
    - 11.0.2
    - 11.1.1
    - 11.1.4
    - 11.1.9
    - 11.2.0
    - 11.3.0
    - 11.4.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: "@octokit/webhooks"
    versions:
    - 7.21.0
    - 7.24.3
    - 8.12.0
    - 8.12.2
    - 8.4.0
    - 8.4.1
    - 8.5.3
    - 8.5.4
    - 8.7.0
    - 8.8.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@semantic-release/github"
    versions:
    - 7.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
