name: 'commit-status-updater'
description: 'Updates the current commit status'
author: 'Ouzi, ltd. Ouzi Team <team@ouzi.dev>'
branding:
  icon: 'check-circle'
  color: 'purple'
inputs:
  context:  
    description: 'The context for the status. Default is GithubActions - ${GITHUB_WORKFLOW}'
  state:  
    description: "Commit state. Possible values are 'pending', 'success', 'error' or 'failure'"
    default: 'pending'
  token:
    description: "The Github token"

runs:
  using: 'docker'
  image: 'Dockerfile'