name: Push test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          name: "testing"
      - name: echo test
        run: |
          echo "this is just a test"
